### ISSUE TITLE
Missing LIcense in the Repo

### ISSUE THREAD

**Issue by Janik-Haag** [octodns/octodns-hetzner#27]
Hey there :D 
I would love to package this for NixOS but it's currently missing a license file and marking it as unfree would be a shame.
The [pypi](https://pypi.org/project/octodns-hetzner/) says that it's licensed under mit, so it would be gerate if you could add that to this repo as well.

**Comment by ross** [comment]
Hrm, just an oversight.

**Comment by ross** [comment]
Fixed by all the linked PRs
