### ISSUE TITLE
Constant repplication of TXT records

### ISSUE THREAD

**Issue by peterablehmann** [octodns/octodns-hetzner#37]
When I set my DKIM keys via octodns, it will try to reapply them on the next run.

When I run octodns it shows that it will update my txt record like this:
```
********************************************************************************
* hetzner (HetznerProvider)
*   Update
*     <TxtRecord TXT 60, default2307._domainkey.xnee.de., ['v=DKIM1\;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyWMWI+s5s12xeAt+lhlOADEd/bemDd8bibDZu6eVYn8om+Gopn68IVyJ5+9SuJ4lkveFzNJagw7X9QRhTMqXI2+DpT1Yo59Z9CeyEhV7BFtsyKwlXTn2oTI3e4fswrQhMhrnUms2oaq+7D5tYo5qI9u7QLtBUnNoFWilaSpbKT+fbQODB8hW7x+af54fBS/+SqeKFSJ91cvoiLiOq+DWRRSqen/4lCFy2YD9HaUvjOsvxcVJHXwW+56fyAgPPquq5jYj8cbE7jcdoRqhx9uBzffLmNNFsRu7SXQBTiARdNpIuIU7/OdsZXHmnaj9RYX4Kyr6FfYSFRjC2sa6S7j56QIDAQAB"']> ->
*     <TxtRecord TXT 60, default2307._domainkey.xnee.de., ['v=DKIM1\;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyWMWI+s5s12xeAt+lhlOADEd/bemDd8bibDZu6eVYn8om+Gopn68IVyJ5+9SuJ4lkveFzNJagw7X9QRhTMqXI2+DpT1Yo59Z9CeyEhV7BFtsyKwlXTn2oTI3e4fswrQhMhrnUms2oaq+7D5tYo5qI9u7QLtBUnNoFWilaSpbKT+fbQODB8hW7x+af54fBS/+SqeKFSJ91cvoiLiOq+DWRRSqen/4lCFy2YD9HaUvjOsvxcVJHXwW+56fyAgPPquq5jYj8cbE7jcdoRqhx9uBzffLmNNFsRu7SXQBTiARdNpIuIU7/OdsZXHmnaj9RYX4Kyr6FfYSFRjC2sa6S7j56QIDAQAB']> ()
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=20
********************************************************************************
```

The only difference between the two is an additional `"` at the end of the key.
After I apply and check again it still shows the same difference.

I've checked the API and the API returns both `"` the one at the beginning as well as the one at the end.

```json
{
      "id": "********************************",
      "type": "TXT",
      "name": "default2307._domainkey",
      "value": "\"v=DKIM1;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyWMWI+s5s12xeAt+lhlOADEd/bemDd8bibDZu6eVYn8om+Gopn68IVyJ5+9SuJ4lkveFzNJagw7X9QRhTMqXI2+DpT1Yo59Z9CeyEhV7BFtsyKwlXTn2oTI3e4fswrQhMhrnUms2oaq+7D5tYo5qI9u7QLtBUnNoFWilaSpbKT+fbQODB8hW7x+af54fBS/+SqeKFSJ91\" \"cvoiLiOq+DWRRSqen/4lCFy2YD9HaUvjOsvxcVJHXwW+56fyAgPPquq5jYj8cbE7jcdoRqhx9uBzffLmNNFsRu7SXQBTiARdNpIuIU7/OdsZXHmnaj9RYX4Kyr6FfYSFRjC2sa6S7j56QIDAQAB\" ",
      "ttl": 60,
      "zone_id": "**********************",
      "created": "2024-05-07 15:55:33.184 +0000 UTC",
      "modified": "2024-05-07 15:55:33.184 +0000 UTC"
}
```

Can someone take a look at this?

**Comment by ross** [comment]
Hrm. There doesn't appear to be any mucking with `"` for TXT records as they come into and get pushed out of octoDNS to Hetzner.

https://github.com/octodns/octodns-hetzner/blob/0bf3dcefe97e550e121973b497645f13711b586b/octodns_hetzner/__init__.py#L126-L132

https://github.com/octodns/octodns-hetzner/blob/0bf3dcefe97e550e121973b497645f13711b586b/octodns_hetzner/__init__.py#L262-L269

The only thing I see in there messing with double-quotes is CAA records. 

You could try throwing debugging `pprints`, of `values` below line 127, and `value` below 263 to see what octoDNS is getting and sending, but I'm not immediately seeing what would remove one of the quotes, but not the other.

It seems odd that the value you're getting back from the API has an escaped double-quote and a space as well. 

Unfortunately I don't have access to Hetzner so I can't poke around myself.

**Comment by peterablehmann** [comment]
How can I make octodns use the local version of the hetzner Provider after I have added the pprints? currently it fails because it does not find the hetznerdns provider.

**Comment by ross** [comment]
`PYTHONPATH=/path/to/octodns-hertzner-root-directory` should do the trick if you've just checked out the code and modified it in that clone.

**Comment by ross** [comment]
Ah. Interesting. Didn't see that the value was "chunked", broken up b/c it's longer then 255 chars. That brings some other code into play, and the bit that's specifically relevant here where the parsing of chunked values happens, and we drop the last character if it appears to be quoted:

https://github.com/octodns/octodns/blob/ed13d2db52b4127f1035a8927a396467219b9918/octodns/record/chunked.py#L65-L66

So what's happening makes sense. The Hetzner API has a spurious space after the `" `, so when we drop the last character assuming it's a double-quote it's actually the space and that leaves the actual double quote.

Not sure whether the fix belongs in octoDNS core, octodns-hetzner, or maybe both. Will have to think about it a bit.

In the meantime you can test it out by changing line 127 to be:

```python
values = [record['value'].replace(';', '\\;').strip() for record in records]
```

**Comment by istr** [comment]
@ross 
> Not sure whether the fix belongs in octoDNS core, octodns-hetzner, or maybe both. Will have to think about it a bit.

It would be great if octoDNS core could handle both cases, with and without (any form of) whitespace between the quotes. Other providers also have similar "quirks".

See https://github.com/octodns/octodns/issues/1088#issuecomment-1763495486 and https://github.com/octodns/octodns/issues/1088#issuecomment-1769209624 and https://github.com/octodns/octodns/issues/1088#issuecomment-1763495481 and https://github.com/octodns/octodns/pull/115/commits

**Comment by ross** [comment]
Yeah that's where I landed. I was 50/50 on whether it should also be fixed here so that an updated octoDNS core wouldn't be required to address the problem. I think I decided that it's not worth it to bother, but if anyone feels otherwise a PR is welcomed.
