### ISSUE TITLE
Root NS records fail to push to Hetzner

### ISSUE THREAD

**Issue by timjackson** [octodns/octodns-hetzner#6]
Environment: octodns_hetzner v0.0.1 and octodns 0.9.17

Although the provider claims to support them, NS records fail to propagate to Hetzner; the following warning message is seen if pushing a zone with a root NS record (e.g. `@ NS ns1.example.com.`) to Hetzner:

`WARNING HetznerProvider[hetzner] root NS record not supported for <domain>.; ignoring it`

Other, non-NS, records are pushed to Hetzner.

Assuming this is not intentional, adding `SUPPORTS_ROOT_NS = True` to `HetznerProvider` solves this issue and NS records are successfully pushed to Hetzner.

**Comment by yzguy** [comment]
Root NS support was added to providers as users submitted the added functionality to specific providers. 
([octodns#876])

Hetzner is one of the providers that it was not added yet in the hopes that someone who had access to Hetzner would take it upon themselves to add it and submit a PR.

Simply by the nature of OctoDNS having support for so many providers, it's not really reasonable for maintainers to have access to all of them, nor have knowledge to maintain all the providers.

**Comment by timjackson** [comment]
My Python skills are rather limited, but I've made an attempt in pull request #7
